site_name: IHC - PCI Concursos
site_description: Documentação do projeto da disciplina de Interação Humano-Computador (FGA-UnB) - Análise e Reprojeto do PCI Concursos
site_author: Equipe Grupo 07 - IHC
site_url: https://Interacao-Humano-Computador.github.io/2026.2-Grupo07/

theme:
  name: material
  language: pt-BR
  logo: assets/images/pci_logo_white.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  
  # Configuração de Cores e Contraste (Modo Claro/Escuro)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o Modo Escuro (Alto Contraste)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Mudar para o Modo Claro

extra_css:
  - stylesheets/extra.css

# Extensões obrigatórias para renderizar tabelas e HTML corretamente
markdown_extensions:
  - tables
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Início: index.md
  - Apresentações: apresentacao/apresentacao-1.md
  - Planejamento 1 (Etapa 1):
    - Equipe: planejamento/membros.md
    - Planejamento do Projeto: planejamento/planejamento-do-projeto.md
    - Heatmap de Disponibilidade: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo-de-design.md
    - Sites Avaliados: planejamento/sites-avaliados.md
    - Site Selecionado: planejamento/site-escolhido.md
    - Atas de Reunião: planejamento/ata-reuniao.md
  - Análise de Requisitos (Etapa 2):
    - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
    - Perfil do Usuário: analise-de-requisitos/perfil-de-usuario.md
    - Personas: analise-de-requisitos/personas.md
    - Cenários: analise-de-requisitos/cenarios.md
    - Análise de Tarefas:
      - HTA: analise-de-requisitos/analise-de-tarefas/hta.md
      - CTT: analise-de-requisitos/analise-de-tarefas/ctt.md
